### PR TITLE
feature: add send-receive pattern restructure folder

### PR DESCRIPTION
**Pull request by gideonairex**
- add send-receive pattern
- restructured folder
- add standard for message type this is to handle dynamically add exchange and queues

### CODE REVIEW

**Comment by fakewaffle** [comment]
I don't think the error handling for the `mixin.extract` is correct.

If I leave out a version `rabbit.response( 'users.findById'` I get the following error:

```
/Source/services/find-one.js:14
			reply( {
			^
TypeError: undefined is not a function
    at User.find.success.error.reply.status (/Source/services/find-one.js:14:4)
    at emit (events.js:95:17)
    at module.exports.CustomEventEmitter.emit (/Source/node_modules/sequelize/lib/emitters/custom-event-emitter.js:61:33)
    at null.<anonymous> (/Source/node_modules/sequelize/lib/query-interface.js:981:19)
    at emit (events.js:95:17)
    at module.exports.CustomEventEmitter.emit (/Source/node_modules/sequelize/lib/emitters/custom-event-emitter.js:61:33)
    at null.<anonymous> (/Source/node_modules/sequelize/lib/emitters/custom-event-emitter.js:131:17)
    at emit (events.js:117:20)
    at module.exports.CustomEventEmitter.emit (/Source/node_modules/sequelize/lib/emitters/custom-event-emitter.js:61:33)
    at module.exports.onSuccess (/Source/node_modules/sequelize/lib/dialects/postgres/query.js:131:14)
```

and not the one as intended:
```
// Check if 3 parameters are existing
if ( tempMeta.length !== 3 ) {
	return callback( new Error( 'Must have proper message type <version>.<resource>.<action>' ) );
}
```

**Comment by gideonairex** [comment]
We are talking about versioning of the messageType so rabbit.response( 'v1.users.findById' ... I think we need to add a version just to explicitly say that we are using this version of service. What you think? We are standardizing the messageType to this <version>.<resource>.<action> so this is mandatory. We also included the version so if we are going to use a new version we will just say v2.users.findById and it will not conflict on the previous one.

**Comment by fakewaffle** [comment]
I completely agree. The only problem seems to be that the correct error
isn't being "thrown" when you don't specify a version.

On Wednesday, January 14, 2015, Gideon Rosales <notifications@github.com>
wrote:

> We are talking about versioning of the messageType so rabbit.response(
> 'v1.users.findById' ... I think we need to add a version just to explicitly
> say that we are using this version of service. What you think? We are
> standardizing the messageType to this .. so this is mandatory. We also
> included the version so if we are going to use a new version we will just
> say v2.users.findById and it will not conflict on the previous one.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/School-Improvement-Network/lapin/pull/5#issuecomment-70017203>
> .
>


-- 
Sent from my iPhone

**Comment by gideonairex** [comment]
ahh okay. I will just fix the error handling. So are you good with that kind of messageType and standardized it?

**Comment by fakewaffle** [comment]
Yep! Take a look at the previous comment as to what is being thrown when
you don't specify the correct type.

On Wednesday, January 14, 2015, Gideon Rosales <notifications@github.com>
wrote:

> ahh okay. I will just fix the error handling. So are you good with that
> kind of messageType and standardized it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/School-Improvement-Network/lapin/pull/5#issuecomment-70017876>
> .
>


-- 
Sent from my iPhone

**Comment by gideonairex** [comment]
Okay thanks! Ill work on it now

**Comment by gideonairex** [comment]
Justin I have changed the reponse and receive. instead of just accepting
```javascript
rabbit.response( 'users.findById', function( options, respond ) {
}
```
it would be 
```javascript
rabbit.response( 'users.findById', function( error, options, respond ) {
}
```

I have decorated the callback and this is also applied in send receive

**Comment by gideonairex** [comment]
Fix the handling of errors. So if it is a wrong messageType it will throw the error

**Pull request merged**
